// MODIFICATION SUMMARY
// - Ensure Google fonts use swap display to reduce blocking and preload warnings (lines 8-14).

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: 'swap', // FIX: add font-display swap
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: 'swap', // FIX: add font-display swap
});

export const metadata: Metadata = {
  title: "CakeJDR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen`} style={{ background: "#13111c" }}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
